"""Output layer of the spotter.

Announcer - output interface. ConsoleAnnouncer prints the event text;
AudioAnnouncer additionally plays a sound file matching the event id.

Sound resolution (first match wins):
    1. audio/<event_id>.mp3     - single hand-placed file
    2. audio/<event_id>_<n>.wav - variants generated by generate_voice.py
                                   (a random one is picked)
    3. otherwise the text is printed plus a [audio] warning

Playback uses the Windows MCI API through ctypes (winmm.dll) - no pip
packages needed, MP3 and WAV are supported by the OS.

AudioAnnouncer plays sounds through a queue (worker thread): phrases do
not overlap and the announcer never cuts itself off mid-word. Events with
a higher priority than the currently playing one preempt it (crash > fuel
> lap info); lower/equal priorities wait their turn.
"""

from __future__ import annotations

import collections
import ctypes
import random
import threading
import time
from datetime import datetime
from pathlib import Path

from .events import SpotterEvent


class Announcer:
    def say(self, event: SpotterEvent) -> None:
        raise NotImplementedError


class ConsoleAnnouncer(Announcer):
    def __init__(self, use_time: bool = True) -> None:
        self._started = time.monotonic()
        self._use_time = use_time

    def say(self, event: SpotterEvent) -> None:
        if self._use_time:
            clock = datetime.now().strftime("%H:%M:%S")
            print(f"[{clock}] {event}")
        else:
            print(str(event))


class AudioAnnouncer(ConsoleAnnouncer):
    def __init__(self, audio_dir: str | Path = "audio",
                 use_time: bool = True) -> None:
        super().__init__(use_time=use_time)
        self.audio_dir = Path(audio_dir)
        self._mci = None
        self._send_fn = None
        self._cv = threading.Condition()
        self._items: collections.deque[tuple[int, list[Path]]] = \
            collections.deque()
        self._worker = threading.Thread(target=self._run_queue, daemon=True)
        self._worker.start()

    def say(self, event: SpotterEvent) -> None:
        super().say(event)
        sounds = self._find_sounds(event.event_id)
        if not sounds:
            print(f"[audio] missing sound file for {event.event_id} in "
                  f"{self.audio_dir} (expected {event.event_id}.mp3 or "
                  f"{event.event_id}_N.wav)")
            return
        with self._cv:
            self._items.append((event.priority, sounds))
            self._cv.notify()

    def _find_sounds(self, event_id: str) -> list[Path]:
        single = self.audio_dir / f"{event_id}.mp3"
        if single.is_file():
            return [single]
        variants = sorted(self.audio_dir.glob(f"{event_id}_[0-9]*.wav"))
        return list(variants)

    def _run_queue(self) -> None:
        while True:
            priority, sounds = self._next_item()
            self._play_blocking(priority, sounds)

    def _next_item(self) -> tuple[int, list[Path]]:
        with self._cv:
            while not self._items:
                self._cv.wait()
            return self._items.popleft()

    def _peek_max_priority(self) -> int:
        with self._cv:
            if not self._items:
                return 0
            return max(p for p, _ in self._items)

    def _play_blocking(self, priority: int, sounds: list[Path]) -> None:
        path = random.choice(sounds)
        if not self._open(path):
            return
        self._send("play spotter from 0")
        while True:
            time.sleep(0.05)
            if self._peek_max_priority() > priority:
                self._send("close spotter")
                return
            if not self._playing():
                self._send("close spotter")
                return

    def _playing(self) -> bool:
        buf = ctypes.create_unicode_buffer(256)
        if self._send("status spotter mode", buf) != 0:
            return False
        return buf.value.lower().strip() == "playing"

    def _open(self, path: Path) -> bool:
        path = path.resolve()
        self._send("close spotter")
        for cmd in (
            f'open "{path}" alias spotter',
            f'open "{path}" type mpegvideo alias spotter',
            f'open "{path}" type waveaudio alias spotter',
        ):
            if self._send(cmd) == 0:
                return True
        print(f"[audio] cannot open sound file: {path}")
        return False

    def _send(self, cmd: str, buf=None) -> int:
        if self._mci is None:
            self._mci = ctypes.WinDLL("winmm", use_last_error=True)
            fn = self._mci.mciSendStringW
            fn.argtypes = [ctypes.c_wchar_p, ctypes.c_wchar_p,
                           ctypes.c_uint, ctypes.c_void_p]
            fn.restype = ctypes.c_uint
            self._send_fn = fn
        return self._send_fn(cmd, buf, ctypes.sizeof(buf) if buf else 0, None)
